### ISSUE TITLE
Getting an 'Array dimensions exceeded supported range.' When trying to use EdiConditional

### ISSUE THREAD

**Issue by cmurphy-omnitracs** [indice-co/EDI.Net#182]
Hi All, 

I'm trying to used EDI conditionals to parse out the individual values of string below:

**L11^UC^DIS~
L11^20210106-UC-4041^CR~
L11^4041^RU~
L11^674.9^ZZ^MI~**

I'm trying to populate the for fields below in my poco
```csharp
  [EdiCondition("DIS", CheckFor = EdiConditionCheckType.Equal, Path = "L11/01")]            
  public QualifiedIdentifier value1 { get; set; }            
  [EdiCondition("CR", Path = "L11/01")]
  [EdiAny]
  public QualifiedIdentifier value2 { get; set; }
  [EdiCondition("RU", Path = "L11/01")]
  [EdiAny]
  public QualifiedIdentifier value3 { get; set; }
  [EdiCondition("ZZ", Path = "L11/01")]
  [EdiAny]
  public QualifiedIdentifier value4 { get; set; }
```
QualifiedIdentifier Class

```csharp
 [EdiSegment, EdiPath("L11")]
 public class QualifiedIdentifier
  {
      [EdiValue("X(2)", Path = "*/00", Description = "Value Part")]
      public string Value { get; set; }
  
      [EdiValue("X(32)", Path = "*/01", Description = "Id part")]
      public string Qualifier { get; set; }
      [EdiValue("X(2)", Path = "*/02", Description = "Id part")]
      public string field3 { get; set; }
  
  
  }
``` 

Here is the error I'm getting 

```
Array dimensions exceeded supported range.
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at indice.Edi.EdiSerializer.SearchForward(EdiReader reader, Queue`1 cache, IEnumerable`1 pathsToSeekForValues)
   at indice.Edi.EdiSerializer.ConditionalMatch(EdiReader reader, EdiStructure currentStructure, EdiStructureType newContainerType, EdiPropertyDescriptor[] candidates)
   at indice.Edi.EdiSerializer.FindForCurrentSegment(EdiReader reader, EdiStructure currentStructure, EdiStructureType newContainerType)
   at indice.Edi.EdiSerializer.TryCreateContainer(EdiReader reader, Stack`1 stack, EdiStructureType newContainer)
   at indice.Edi.EdiSerializer.DeserializeInternal(EdiReader reader, Type objectType)
   at indice.Edi.EdiSerializer.Deserialize[T](TextReader reader, IEdiGrammar grammar)
```

I'm not exactly sure what I'm doing wrong with the EdiConditions. Any help will be much appreciated

**Comment by cleftheris** [comment]
Hi Charles and thanks for your interest in the library. 
The best way to get help would be to create a sample transmission and a sample model with a failing test. Adding that to the test project and make a pull request would immediately showcase the issue and potentially contribute to resolving a bug. 

Generally you seem to be doing everything right. Some thoughts worth noting: 
1. the delimiters on the transmission sample are not the usual ones as far as I can see . I would expect you are configuring your `EdiGrammar` accordingly. 
2. Second thing I noticed is that the `Path` on the EdiCondition attribute uses "padding" on the indexers (01 instead of 1 etc.) so I your get rid of that too. 

C.

**Comment by cmurphy-omnitracs** [comment]
Hi I was able to figure it out

**Comment by Yolcar** [comment]
@cmurphy-omnitracs how resolve?
